call plug#begin('~/.nvim/plugged')

Plug 'junegunn/seoul256.vim'
Plug 'kien/ctrlp.vim'
Plug 'mattn/emmet-vim'

call plug#end()


" Color Scheme
" Unified color scheme (default: dark)
colo seoul256

" Light color scheme
colo seoul256-light

" Switch
set background=dark



" Hot keys
" let g:ctrlp_map = '<D-p>'

" redefine emmet hot key with tab
imap <expr> <tab> emmet#expandAbbrIntelligent("\<tab>")
