call plug#begin('~/.nvim/plugged')

Plug 'junegunn/seoul256.vim'

call plug#end()


" Unified color scheme (default: dark)
colo seoul256

" Light color scheme
colo seoul256-light

" Switch
set background=dark
