#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi



# Customize to your needs...
ulimit -n 10000



# Aliases
alias glog='git log --graph --pretty=format:"%C(yellow)%h %C(white)- %ar, %C(cyan)[%an] %C(white normal): %s"'
alias greset='git reset head --hard'
# remove all branches except master
alias gbremove="git branch | grep -v "master" | xargs git branch -D"

alias mserver='mongod --config /usr/local/etc/mongod.conf'

gdiff() {
	git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative $1..$2
}


# iterm tab color
# usage >> tab-color 255 0 0
tab-color() {
    echo -ne "\033]6;1;bg;red;brightness;$1\a"
    echo -ne "\033]6;1;bg;green;brightness;$2\a"
    echo -ne "\033]6;1;bg;blue;brightness;$3\a"
}

tab-reset() {
    echo -ne "\033]6;1;bg;*;default\a"
}

# Start an HTTP server from a directory, optionally specifying the port
function server() {
	local port="${1:-8000}";
	sleep 1 && open "http://localhost:${port}/" &
	# Set the default Content-Type to `text/plain` instead of `application/octet-stream`
	# And serve everything as UTF-8 (although not technically correct, this doesn’t break anything for binary files)
	python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port";
}


# commit all with current branch prepended
function gcam() {
		BRANCH=$(git branch -l | grep '*' | awk '{print $2}')
		git commit -am "${BRANCH}. ${1}"
}

# remove zprezto alias
unalias gcm
# commit only files add stage with current branch prepended
function gcm() {
		BRANCH=$(git branch -l | grep '*' | awk '{print $2}')
		git commit -m "${BRANCH}. ${1}"
}


# force update cask
function bcaskupdate() {
	brew update
	brew cleanup
	brew cask update
	brew cask cleanup
	brew cask uninstall --force $1
	brew cask install $1
}

function fixbrew() {
	# untap all cask repositories
	brew untap caskroom/homebrew-cask
	brew untap phinze/homebrew-cask
	# remove all remaining pieces
	rm -rf $(brew --prefix)/Library/Taps/phinze-cask
	rm $(brew --prefix)/Library/Formula/brew-cask.rb
	rm -rf $(brew --prefix)/Library/Taps/caskroom
	# finish up
	brew uninstall --force brew-cask
	brew update; brew cleanup; brew cask cleanup
}




alias gd='git difftool .'
alias gdc='git difftool --cached .'




export PROJECT_HOME=$HOME/dev/Projects
export ESPORTS_HOME=$HOME/dev/Projects/esports/esports_git
export TMS_HOME=$HOME/dev/Projects/TMS


#virtualenv wrapper
export WORKON_HOME=$HOME/dev/Projects/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting


